"""new fields in user m model

Revision ID: 920d92fc09fe
Revises: 5e0dee8125ab
Create Date: 2019-08-27 08:42:01.840673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920d92fc09fe'
down_revision = '5e0dee8125ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
